################################# Default configuration ###################
# provide your domain here
baseURL = "//help.now.cn/"
# theme
theme = "dot"
# site title
title = "时代互联帮助中心"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
DefaultContentLanguage = "cn"


# unsafe html
[markup.goldmark.renderer]
unsafe= true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title"]
appId = "C5NKCUUKY3"
indexName = "help.now.cn"
searchOnlyKey = "62ade335eecc204c0f250e8c917f658b"

################################# navigation ################################

[[menu.main]]
name = "域名问题"
url = "/domain"
weight = 2
[[menu.main]]
name = "云虚拟主机问题"
url = "/vhost"
weight = 3
[[menu.main]]
name = "SSL证书问题"
url = "/ssl"
weight = 4
[[menu.main]]
name = "文档下载"
url = "https://www.now.cn/support/doc.php"
weight = 5

################################# friends links ################################
[[params.first_line]]
text = "关于我们"
url = "https://now.cn/aboutus/"
[[params.first_line]]
text = "联系我们"
url = "https://now.cn/customer/contact.php"
[[params.first_line]]
text = "交费确认"
url = "https://now.cn/user/login.php"
[[params.first_line]]
text = "友情链接"
url = "https://now.cn/associate/link.php"
[[params.first_line]]
text = "注册者的义务和权力"
url = "https://www.icann.org/resources/pages/responsibilities-2014-03-14-zh"
[[params.first_line]]
text = "手机客户端"
url = "https://now.cn/app/"

[[params.second_line]]
text = "友情链接："
url = ""
[[params.second_line]]
text = "时代互联国际站"
url = "http://hk.now.top/"
[[params.second_line]]
text = "手机站"
url = "https://m.now.cn/"
[[params.second_line]]
text = "English"
url = "https://www.now.top/"
[[params.second_line]]
text = "繁体站"
url = "https://www.tnet.hk/"
[[params.second_line]]
text = "优品智能"
url = "http://www.top.sh/"
[[params.second_line]]
text = "域名注册"
url = "https://now.cn/domain/index.php"
[[params.second_line]]
text = "域名交易"
url = "https://e.now.cn/"
[[params.second_line]]
text = "虚拟主机"
url = "https://now.cn/vhost/index.php"
[[params.second_line]]
text = "DNS.COM"
url = "https://www.dns.com/"
[[params.second_line]]
text = "锐成云分销"
url = "https://www.racent.com/"
[[params.second_line]]
text = "友情链接"
url = "https://now.cn/associate/link.php"
############################# Default Parameters ##########################
[params]
# logo is for all page
logo = "images/logo.jpg"
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

certUrl = "https://now.cn/aboutus/cert.php"
certText_left = "ICANN & CNNIC 国内海外顶级双域名注册商"
certText_right = " | 20年全球百万用户选择时代互联"
nowcn_text = "时代互联官网"
nowcn_link = "https://www.now.cn/"
agent_text = "代理平台"
agent_link = "http://www.todaynic.com/"
domain_text = "域名交易"
domain_link = "https://e.now.cn/"
pay_text = "支付方式"
pay_link = "https://www.now.cn/support/pay.php"
contact_text = "联系我们"
contact_link = "https://now.cn/customer/contact.php"
nav_phone = "全国统一热线：4006-123-688"
subtitle = "帮助中心"
keywords="Todaynic.com,Todaynic,todaynic.com,域名代理,虚拟主机代理,短信平台代理,域名注册,注册域名,中文域名,虚拟主机,企业邮箱,云主机,服务器租用,短信平台,企业服务,商标注册,网站建设,注册香港公司"
description="时代互联是虚拟专用服务器空间提供商,全国10强,20年专业提供域名注册、海内外虚拟主机、云服务器、云主机、企业邮箱、智能建站、服务器租用、服务器托管等优秀服务,百万用户的共同选择"

copyright = "Copyright © 2000- 2020 Todaynic.com,Inc. All Rights Reserved."
icpicon="//s.now.cn/special/images/gh.png"
icp = "公安备案号 44040202000047"
beian = "粤 B1.B2-20042046"
icplink = "http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=44040202000047"
beianlink = "http://beian.miit.gov.cn/"

# customize color
primary_color = "#f60"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io

################################# submenu ################################
[[params.submenu]]
src = "images/gd.png"
name = "提交工单"
url = "https://now.cn/user/ticket.php"

[[params.submenu]]
src = "images/customer_service.png"
name = "在线客服"
url = "javascript:;"
weight = 2

################################ Chinese Language ######################
[Languages.cn]
languageName = "中文"
languageCode = "cn"
weight = 1
home = "首页"
# banner
[Languages.cn.params.banner]
title = "时代互联帮助中心"
subtitle = "快速从我们的网站中找到建议和答案，或者联系我们"
bg_image = "images/banner.jpg"
placeholder = "有问题吗？在这里询问或输入条件"



