################################# Default configuration ###################
# provide your domain here
baseURL = "/"
# theme
theme = "dot"
# site title 
title = "欢迎使用"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
DefaultContentLanguage = "cn"
enableRobotsTXT = true
# unsafe html
[markup.goldmark.renderer]
unsafe= true

[outputs]
    home = ["HTML", "RSS", "Algolia"]
	
[outputFormats.Algolia]
  baseName = "algolia"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true
  
[params.algolia]
  vars = ["title"]
  appId = "Q2DLLGTW9U"
  indexName = "www.hello-api.cn"
  searchOnlyKey = "b50572fce929a1c483f47817811a0e2c"
  
################################# navigation ################################

[[menu.main]]
name = "PHP"
url = "/php"
weight = 2
[[menu.main]]
name = "Python"
url = "/python"
weight = 3
[[menu.main]]
name = "最新资讯"
url = "/news"
weight = 4

################################# friends links ################################
# [[params.first_line]]
# text = "手机客户端"
# url = "/"

# [[params.second_line]]
# text = "友情链接："
# url = ""
############################# Default Parameters ##########################
[params]
# logo is for all page
logo = "images/favicon.png"
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

subtitle = "个人博客"
keywords=""
description=""

copyright = ""
beian = "粤ICP备19150058号"
icplink = "http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=44040202000047"
beianlink = "http://beian.miit.gov.cn/"

# customize color
primary_color = "#3c8dBc"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io

################################# submenu ################################
[[params.submenu]]
name = "Github"
src = "images/github.png"
url = "https://github.com/suguer"


################################ Chinese Language ######################
[Languages.cn]
languageName = "中文"
languageCode = "cn"
weight = 1
home = "首页"
# banner
[Languages.cn.params.banner]
title = "欢迎使用时代互联帮助中心"
bg_image = "images/banner-bg.png"
placeholder = "有问题吗？在这里询问或输入条件"



